nodeLinker: node-modules

# https://yarnpkg.com/getting-started/migration/#dont-use-npmrc-files
# npmAuthToken: ${NPM_TOKEN}
# YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
npmPublishAccess: 'public'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-berry.cjs
